local props = {
	cost = 1000,
	costType = "Dice",
	items = {
		"Hat Black Ninja Headband",
		"Hat Blue & Black Visor",
		"Hat Blue Beanie",
		"Hat Blue Snorkel",
		"Hat Boom's Antenna",
		"Hat Bucket",
		"Hat Camera",
		"Hat Comedy Mask",
		"Hat Cracked Egg",
		"Hat Dice Hat",
		"Hat Drama Mask",
		"Hat Epic Duck",
		"Hat Explorer's Hat",
		"Hat Fedora",
		"Hat Fez",
		"Hat Fricko's Antennas",
		"Hat Golden Top Hat of Bling Bling",
		"Hat Graduate's Cap",
		"Hat Gygax",
		"Hat Headphones",
		"Hat Hockey Mask",
		"Hat Incognito Glasses",
		"Hat Lampshade",
		"Hat Leprechaun Tophat",
		"Hat Money Cap",
		"Hat Mouse Ears",
		"Hat News Boat",
		"Hat Police Cap",
		"Hat Pot",
		"Hat Purple Banded Tophat",
		"Hat Purple Pumpkin",
		"Hat Purple Snorkel",
		"Hat Purple Squid",
		"Hat Red & White Visor",
		"Hat Red Beanie",
		"Hat Robber's Beanie",
		"Hat Roblox Cap",
		"Hat Soldier's Helmet",
		"Hat Squid",
		"Hat Traffic Cone",
		"Hat Umbrella Hat",
		"Hat White Ninja Headband"
	}
}

return props